name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "**"

jobs:
  run_tests:
    name: tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]
        toxenv: [quality, django42]

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Clone zeitlabs-payments
        run: |
          git clone --branch tehreem/fix_small_issues --single-branch https://github.com/zeit-labs/zeitlabs-payments.git ../zeitlabs-payments

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pip
        run: pip install -r requirements/pip.txt

      - name: Install Dependencies
        run: pip install -r requirements/ci.in

      - name: Run Tests
        env:
          TOXENV: ${{ matrix.toxenv }}
        run: tox
